// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpzwLQwNkq5dze2-i7-bDG34NadwLJWWM',
    appId: '1:1047836833789:web:64f991a254a91fb0064b94',
    messagingSenderId: '1047836833789',
    projectId: 'wtl-cms-saas',
    authDomain: 'wtl-cms-saas.firebaseapp.com',
    storageBucket: 'wtl-cms-saas.appspot.com',
    measurementId: 'G-HF5B5ENLFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9rWq4NhNqlyRVtRjTPhi1mcWi0Dafruc',
    appId: '1:1047836833789:android:2cc473950c7546cb064b94',
    messagingSenderId: '1047836833789',
    projectId: 'wtl-cms-saas',
    storageBucket: 'wtl-cms-saas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2pm6s5zHJmUAWT-tR1jXaDDNqUQ95xEs',
    appId: '1:1047836833789:ios:d9f5c35f7816e7df064b94',
    messagingSenderId: '1047836833789',
    projectId: 'wtl-cms-saas',
    storageBucket: 'wtl-cms-saas.appspot.com',
    iosClientId: '1047836833789-22djtpknalh9iauk8176m296qh2rh51c.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2pm6s5zHJmUAWT-tR1jXaDDNqUQ95xEs',
    appId: '1:1047836833789:ios:b4961ca628839629064b94',
    messagingSenderId: '1047836833789',
    projectId: 'wtl-cms-saas',
    storageBucket: 'wtl-cms-saas.appspot.com',
    iosClientId: '1047836833789-bn2jbvo4n7ng25guubimbjjf61t2sddu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile.RunnerTests',
  );
}
